export var filters = [
    {
        "name": "filter-market-cap", "filters": [
            { "value": '[{"field":"market_cap", "type":">=", "value":8092830}]', 'text': 'Mega (100B and more)' },
            { "value": '[{ "field": "market_cap", "type":">=", "value":10000000000},{ "field": "market_cap", "type":"<=", "value":99999999999}]', 'text': 'Large (10B up to 100B)' },
            { "value": '[{ "field": "market_cap", "type": ">=", "value":1000000000},{ "field": "market_cap", "type": "<=", "value":9999999999}]', 'text': 'Mid ( 1B to 10B)' },
            { "value": '[{ "field": "market_cap", "type": ">=", "value":500000000}, { "field": "market_cap", "type": "<=", "value":999999999}]', 'text': 'Small ( 500M to 1B)' },
            { "value": '[{ "field": "market_cap", "type": ">=", "value":100000000}, {"field": "market_cap", "type": "<=", "value":499999999}]', 'text': 'Micro ( 100M to 500M)' },
            { "value": '[{ "field": "market_cap", "type": ">=", "value":100000000}]', 'text': 'Nano (Up to 100M)' }
        ]
    },
    {
        "name": "filter-index", "filters": [
            { "value": '[{"field":"index","type":"=","value":"MASI"}]', 'text': 'MASI' },
            { "value": '[{"field":"index","type":"=","value":"DSI"}]', 'text': 'DSI' },
            { "value": '[{"field":"index","type":"=","value":"FSI"}]', 'text': 'FSI' }
        ]
    }, {
        "name": "filter-exchange", "filters": [
            { "value": '[{"field":"exchange","type":"=","value":"MSE"}]', 'text': 'MSE' },
            { "value": '[{"field":"exchange","type":"=","value":"DSI"}]', 'text': 'BSE' },
            { "value": '[{"field":"exchange","type":"=","value":"FSI"}]', 'text': 'SEM' },
            { "value": '[{"field":"exchange","type":"=","value":"FSI"}]', 'text': 'JSE' }
        ]
    }, {
        "name": "filter-country", "filters": [
            { "value": '[{"field":"country","type":"=","value":"Botswana"}]', 'text': 'Botswana' },
            { "value": '[{"field":"country","type":"=","value":"Malawi"}]', 'text': 'Malawi' },
            { "value": '[{"field":"country","type":"=","value":"Mauritius"}]', 'text': 'Mauritius' },
            { "value": '[{"field":"country","type":"=","value":"South Africa"}]', 'text': 'South Africa' }
        ]
    }
    , {
        "name": "filter-div-yield", "filters": [
            { "value": '[{"field":"div_yield","type":">","value":0.05}]', 'text': '>5%' },
            { "value": '[{"field":"div_yield","type":">=","value":0.025},{"field":"div_yield","type":"<=","value":0.05}]', 'text': '2.5% to 5%' },
            { "value": '[{"field":"div_yield","type":">=","value":0.005},{"field":"div_yield","type":"<","value":0.025}]', 'text': '0.5% - 2.5%' },
            { "value": '[{"field":"div_yield","type":"<","value":0.005}]', 'text': '<0.5%' }]
    }
    , {
        "name": "filter-avg-volume", "filters": [
            { "value": '[{"field":"avg_volume","type":">=","value":1000000}]', 'text': '>= 1Million' },
            { "value": '[{"field":"avg_volume","type":">=","value":100000},{"field":"avg_volume","type":"<=","value":999999}]', 'text': '100,000 - 999,999 ' },
            { "value": '[{"field":"avg_volume","type":">=","value":10000},{"field":"avg_volume","type":"<=","value":99999}]', 'text': '10,000 - 99,999' },
            { "value": '[{"field":"avg_volume","type":">=","value":1000},{"field":"avg_volume","type":"<=","value":9999}]', 'text': '1,000 - 9,999' },
            { "value": '[{"field":"avg_volume","type":"<","value":1000}]', 'text': '<= 1000' }]
    }, {
        "name": "filter-curr-volume", "filters": [
            { "value": '[{"field":"volume","type":">=","value":1000000}]', 'text': '>= 1Million' },
            { "value": '[{"field":"volume","type":">=","value":100000},{"field":"volume","type":"<=","value":999999}]', 'text': '100,000 to 999,999 ' },
            { "value": '[{"field":"volume","type":">=","value":10000},{"field":"volume","type":"<=","value":99999}]', 'text': '10,000 to 99,999' },
            { "value": '[{"field":"volume","type":">=","value":1000},{"field":"volume","type":"<=","value":9999}]', 'text': '1,000 to 9,999' },
            { "value": '[{"field":"volume","type":"<","value":1000}]', 'text': '<= 1000' }]
    }
    , {
        "name": "filter-ipo-date", "filters": [
            { "value": '[{"field":"ipo_date","type":">=","value":"2018-01-01"}]', 'text': '>= 2018' },
            { "value": '[{"field":"ipo_date","type":">=","value":"2015-01-01"},{"field":"ipo_date","type":"<=","value":"2017-12-31"}]', 'text': '2015 - 2017' },
            { "value": '[{"field":"ipo_date","type":">=","value":"2012-01-01"},{"field":"ipo_date","type":"<=","value":"2014-12-31"}]', 'text': '2012 - 2014 ' },
            { "value": '[{"field":"ipo_date","type":">=","value":"2009-01-01"},{"field":"ipo_date","type":"<=","value":"2011-31-12"}]', 'text': '2009 - 2011' },
            { "value": '[{"field":"ipo_date","type":">=","value":"2006-01-01"},{"field":"ipo_date","type":"<=","value":"2008-12-31"}]', 'text': '2006 - 2008' },
            { "value": '[{"field":"ipo_date","type":">=","value":"2003-01-01"},{"field":"ipo_date","type":"<=","value":"2005-12-31"}]', 'text': '2003 - 2005' },
            { "value": '[{"field":"ipo_date","type":">=","value":"2000-01-01"},{"field":"ipo_date","type":"<=","value":"2002-12-31"}]', 'text': '2000 - 2002' },
            { "value": '[{"field":"ipo_date","type":">=","value":"1997-01-01"},{"field":"ipo_date","type":"<=","value":"1999-12-31"}]', 'text': '1997 - 1999' },
            { "value": '[{"field":"ipo_date","type":">=","value":"1994-01-01"},{"field":"ipo_date","type":"<=","value":"1996-12-31"}]', 'text': '1994 - 1996' },
            { "value": '[{"field":"ipo_date","type":">=","value":"1991-01-01"},{"field":"ipo_date","type":"<=","value":"1993-12-31"}]', 'text': '1991 - 1993' },
            { "value": '[{"field":"ipo_date","type":"<","value":"1990-12-31"}]', 'text': '<= 1990' }]
    }
    , {
        "name": "filter-sector", "filters": [
            { "value": '[{"field":"sector","type":"like","value":"basic"}]', 'text': 'Basic Materials' },
            { "value": '[{"field":"sector","type":"like","value":"consumer"}]', 'text': 'Consumer Staples' },
            { "value": '[{"field":"sector","type":"like","value":"consumer"}]', 'text': 'Consumer Discretionary' },
            { "value": '[{"field":"sector","type":"like","value":"real estate"}]', 'text': 'Real Estate' },
            { "value": '[{"field":"sector","type":"like","value":"financials"}]', 'text': 'Financials' },
            { "value": '[{"field":"sector","type":"like","value":"industrial"}]', 'text': 'Industrial Goods' },
            { "value": '[{"field":"sector","type":"like","value":"services"}]', 'text': 'Services' },
            { "value": '[{"field":"sector","type":"like","value":"technology"}]', 'text': 'Technology' },
            { "value": '[{"field":"sector","type":"like","value":"utilities"}]', 'text': 'Utilities' }]
    }
    , {
        "name": "filter-industry", "filters": [
            { "value": '[{"field":"industry","type":"like","value":"asset"}]', 'text': 'Financial Services' },
            //{ "value": '[{"field":"industry","type":"=","value":"banking_retail"}]', 'text': 'Banking - Retail' },
            { "value": '[{"field":"industry","type":"like","value":"bank"}]', 'text': 'Banking' },
            //{ "value": '[{"field":"industry","type":"=","value":"consumer_goods_retail"}]', 'text': 'Consumer Goods Retail' },
            //{ "value": '[{"field":"industry","type":"like","value":"manufacturing"}]', 'text': 'Consumer Goods Man.' },
            { "value": '[{"field":"industry","type":"like","value":"diversified"}]', 'text': 'Diversified Financials' },
            { "value": '[{"field":"industry","type":"like","value":"hotel"}]', 'text': 'Hotels & Restaurants' },
            { "value": '[{"field":"industry","type":"like","value":"it services"}]', 'text': 'IT Services' },
            { "value": '[{"field":"industry","type":"like","value":"telecomm"}]', 'text': 'Telecommunication' },
            { "value": '[{"field":"industry","type":"like","value":"real estate"}]', 'text': 'Real Estate Development' }]
    }
    , {
        "name": "filter-pe", "filters": [
            { "value": '[{"field":"PE", "type":">", "value":5}]', 'text': 'Over 5' },
            { "value": '[{"field":"PE", "type":">", "value":10}]', 'text': 'Over 10' },
            { "value": '[{"field":"PE", "type":">", "value":15}]', 'text': 'Over 15' },
            { "value": '[{"field":"PE", "type":">", "value":20}]', 'text': 'Over 20' },
            { "value": '[{"field":"PE", "type":">", "value":25}]', 'text': 'Over 25' },
            { "value": '[{"field":"PE", "type":">", "value":30}]', 'text': 'Over 30' },
            { "value": '[{"field":"PE", "type":">", "value":35}]', 'text': 'Over 35' },
            { "value": '[{"field":"PE", "type":">", "value":50}]', 'text': 'Over 50' },
            { "value": '[{"field":"PE", "type":"<", "value":5}]', 'text': 'Less than 5' },
            { "value": '[{"field":"PE", "type":"<", "value":10}]', 'text': 'Less than 10' },
            { "value": '[{"field":"PE", "type":"<", "value":15}]', 'text': 'Less than 15' },
            { "value": '[{"field":"PE", "type":"<", "value":25}]', 'text': 'Less than 25' },
            { "value": '[{"field":"PE", "type":"<", "value":30}]', 'text': 'Less than 30' }]
    }
    , {
        "name": "filter-peg", "filters": [
            { "value": '[{"field":"peg", "type":">", "value":3}]', 'text': 'Over 3' },
            { "value": '[{"field":"peg", "type":">", "value":2}]', 'text': 'Over 2' },
            { "value": '[{"field":"peg", "type":">=", "value":1}]', 'text': 'Over 1' },
            { "value": '[{"field":"peg", "type":"<=", "value":3}]', 'text': 'Less than 3' },
            { "value": '[{"field":"peg", "type":"<=", "value":2}]', 'text': 'Less than 2' },
            { "value": '[{"field":"peg", "type":"<=", "value":20}]', 'text': 'Less than 1' }]
    }
    , {
        "name": "filter-ps", "filters": [
            { "value": '[{"field":"PS", "type":">", "value":10}]', 'text': 'Over 10' },
            { "value": '[{"field":"PS", "type":">", "value":8}]', 'text': 'Over 8' },
            { "value": '[{"field":"PS", "type":">", "value":6}]', 'text': 'Over 6' },
            { "value": '[{"field":"PS", "type":">", "value":5}]', 'text': 'Over 5' },
            { "value": '[{"field":"PS", "type":">", "value":4}]', 'text': 'Over 4' },
            { "value": '[{"field":"PS", "type":">", "value":3}]', 'text': 'Over 3' },
            { "value": '[{"field":"PS", "type":">", "value":2}]', 'text': 'Over 2' },
            { "value": '[{"field":"PS", "type":">", "value":1}]', 'text': 'Over 1' },
            { "value": '[{"field":"PS", "type":"<=", "value":10}]', 'text': 'Under 10' },
            { "value": '[{"field":"PS", "type":"<=", "value":8}]', 'text': 'Under 8' },
            { "value": '[{"field":"PS", "type":"<=", "value":6}]', 'text': 'Under 6' },
            { "value": '[{"field":"PS", "type":"<=", "value":5}]', 'text': 'Under 5' },
            { "value": '[{"field":"PS", "type":"<=", "value":4}]', 'text': 'Under 4' },
            { "value": '[{"field":"PS", "type":"<=", "value":3}]', 'text': 'Under 3' },
            { "value": '[{"field":"PS", "type":"<=", "value":2}]', 'text': 'Under 2' },
            { "value": '[{"field":"PS", "type":"<=", "value":1}]', 'text': 'Under 1' }]
    }
    , {
        "name": "filter-pbv", "filters": [
            { "value": '[{"field":"pbv", "type":">", "value":10}]', 'text': 'Over 10' },
            { "value": '[{"field":"pbv", "type":">", "value":8}]', 'text': 'Over 8' },
            { "value": '[{"field":"pbv", "type":">", "value":6}]', 'text': 'Over 6' },
            { "value": '[{"field":"pbv", "type":">", "value":5}]', 'text': 'Over 5' },
            { "value": '[{"field":"pbv", "type":">", "value":4}]', 'text': 'Over 4' },
            { "value": '[{"field":"pbv", "type":">", "value":3}]', 'text': 'Over 3' },
            { "value": '[{"field":"pbv", "type":">", "value":2}]', 'text': 'Over 2' },
            { "value": '[{"field":"pbv", "type":">", "value":1}]', 'text': 'Over 1' },
            { "value": '[{"field":"pbv", "type":"<=", "value":10}]', 'text': 'Under 10' },
            { "value": '[{"field":"pbv", "type":"<=", "value":8}]', 'text': 'Under 8' },
            { "value": '[{"field":"pbv", "type":"<=", "value":6}]', 'text': 'Under 6' },
            { "value": '[{"field":"pbv", "type":"<=", "value":5}]', 'text': 'Under 5' },
            { "value": '[{"field":"pbv", "type":"<=", "value":4}]', 'text': 'Under 4' },
            { "value": '[{"field":"pbv", "type":"<=", "value":3}]', 'text': 'Under 3' },
            { "value": '[{"field":"pbv", "type":"<=", "value":2}]', 'text': 'Under 2' },
            { "value": '[{"field":"pbv", "type":"<=", "value":1}]', 'text': 'Under 1' }]
    }

    , {
        "name": "filter-eps", "filters": [
            { "value": '[{"field":"EPS", "type":">", "value":30}]', 'text': 'Over 30' },
            { "value": '[{"field":"EPS", "type":">", "value":25}]', 'text': 'Over 25' },
            { "value": '[{"field":"EPS", "type":">", "value":10}]', 'text': 'Over 10' },
            { "value": '[{"field":"EPS", "type":">", "value":5}]', 'text': 'Over 5' },
            { "value": '[{"field":"EPS", "type":"<", "value":30}]', 'text': 'Below 30' },
            { "value": '[{"field":"EPS", "type":"<", "value":20}]', 'text': 'Below 20' },
            { "value": '[{"field":"EPS", "type":"<", "value":10}]', 'text': 'Below 10' },
            { "value": '[{"field":"EPS", "type":"<", "value":5}]', 'text': 'Below 5' },
            { "value": '[{"field":"EPS", "type":"<", "value":0}]', 'text': 'Negative (< 0)' }]
    },
    {
        "name": "filter-eps-g-1y", "filters": [
            { "value": '[{"field":"eps_g_1y", "type":"<", "value":0}]', 'text': 'Negative (< 0%)' },
            { "value": '[{"field":"eps_g_1y", "type":">", "value":0}]', 'text': 'Positive (> 0%)' },
            { "value": '[{"field":"eps_g_1y", "type":">", "value":15}]', 'text': 'Positive Low (1% - 10%)' },
            { "value": '[{"field":"eps_g_1y", "type":">", "value":0.2}]', 'text': 'High (>20%)' },
            { "value": '[{"field":"eps_g_1y", "type":">", "value":0.25}]', 'text': 'Over 25%' },
            { "value": '[{"field":"eps_g_1y", "type":">", "value":0.20}]', 'text': 'Over 20%' },
            { "value": '[{"field":"eps_g_1y", "type":">", "value":0.15}]', 'text': 'Over 15%' },
            { "value": '[{"field":"eps_g_1y", "type":">", "value":0.10}]', 'text': 'Over 10%' },
            { "value": '[{"field":"eps_g_1y", "type":">", "value":0.05}]', 'text': 'Over 5%' },
            { "value": '[{"field":"eps_g_1y", "type":">", "value":0.03}]', 'text': 'Over 3%' },
            { "value": '[{"field":"eps_g_1y", "type":">", "value":0.02}]', 'text': 'Over 2%' },
            { "value": '[{"field":"eps_g_1y", "type":"<", "value":0.30}]', 'text': 'Under 30%' },
            { "value": '[{"field":"eps_g_1y", "type":"<", "value":0.25}]', 'text': 'Under 25%' },
            { "value": '[{"field":"eps_g_1y", "type":"<", "value":0.20}]', 'text': 'Under 20%' },
            { "value": '[{"field":"eps_g_1y", "type":"<", "value":0.15}]', 'text': 'Under 15%' },
            { "value": '[{"field":"eps_g_1y", "type":"<", "value":0.10}]', 'text': 'Under 10%' },
            { "value": '[{"field":"eps_g_1y", "type":"<", "value":0.05}]', 'text': 'Under 5%' },
            { "value": '[{"field":"eps_g_1y", "type":"<", "value":0.03}]', 'text': 'Under 3%' },
            { "value": '[{"field":"eps_g_1y", "type":"<", "value":0.02}]', 'text': 'Under 2%' }]
    },
    {
        "name": "filter-payout-ratio", "filters": [
            { "value": '[{"field":"payout_ratio", "type":">", "value":0.2}]', 'text': 'High (>70%)' },
            { "value": '[{"field":"payout_ratio", "type":">", "value":0.25}]', 'text': 'Over 25%' },
            { "value": '[{"field":"payout_ratio", "type":">", "value":0.20}]', 'text': 'Over 20%' },
            { "value": '[{"field":"payout_ratio", "type":">", "value":0.15}]', 'text': 'Over 15%' },
            { "value": '[{"field":"payout_ratio", "type":">", "value":0.10}]', 'text': 'Over 10%' },
            { "value": '[{"field":"payout_ratio", "type":">", "value":0.05}]', 'text': 'Over 5%' },
            { "value": '[{"field":"payout_ratio", "type":">", "value":0.03}]', 'text': 'Over 3%' },
            { "value": '[{"field":"payout_ratio", "type":">", "value":0.02}]', 'text': 'Over 2%' },
            { "value": '[{"field":"payout_ratio", "type":"<", "value":0.30}]', 'text': 'Under 30%' },
            { "value": '[{"field":"payout_ratio", "type":"<", "value":0.25}]', 'text': 'Under 25%' },
            { "value": '[{"field":"payout_ratio", "type":"<", "value":0.20}]', 'text': 'Under 20%' },
            { "value": '[{"field":"payout_ratio", "type":"<", "value":0.15}]', 'text': 'Under 15%' },
            { "value": '[{"field":"payout_ratio", "type":"<", "value":0.10}]', 'text': 'Under 10%' },
            { "value": '[{"field":"payout_ratio", "type":"<", "value":0.05}]', 'text': 'Under 5%' },
            { "value": '[{"field":"payout_ratio", "type":"<", "value":0.03}]', 'text': 'Under 3%' },
            { "value": '[{"field":"payout_ratio", "type":"<", "value":0.02}]', 'text': 'Under 2%' }]
    }

    , {
        "name": "filter-eps-g-5y", "filters": [
            { "value": '[{"field":"eps_g_5y", "type":"<", "value":0}]', 'text': 'Negative (< 0%)' },
            { "value": '[{"field":"eps_g_5y", "type":">", "value":0}]', 'text': 'Positive (> 0%)' },
            { "value": '[{"field":"eps_g_5y", "type":">", "value":0.01}, {"field":"eps_g_5y", "type":"<=", "value":0.01}]', 'text': 'Positive Low (1% - 10%)' },
            { "value": '[{"field":"eps_g_5y", "type":">", "value":0.2}]', 'text': 'High (>20%)' },
            { "value": '[{"field":"eps_g_5y", "type":">", "value":0.30}]', 'text': 'Over 30% ' },
            { "value": '[{"field":"eps_g_5y", "type":">", "value":0.25}]', 'text': 'Over 25%' },
            { "value": '[{"field":"eps_g_5y", "type":">", "value":0.20}]', 'text': 'Over 20%' },
            { "value": '[{"field":"eps_g_5y", "type":">", "value":0.15}]', 'text': 'Over 15%' },
            { "value": '[{"field":"eps_g_5y", "type":">", "value":0.10}]', 'text': 'Over 10%' },
            { "value": '[{"field":"eps_g_5y", "type":">", "value":0.05}]', 'text': 'Over 5%' },
            { "value": '[{"field":"eps_g_5y", "type":">", "value":0.03}]', 'text': 'Over 3%' },
            { "value": '[{"field":"eps_g_5y", "type":">", "value":0.02}]', 'text': 'Over 2%' },
            { "value": '[{"field":"eps_g_5y", "type":"<", "value":0.30}]', 'text': 'Under 30%' },
            { "value": '[{"field":"eps_g_5y", "type":"<", "value":0.25}]', 'text': 'Under 25%' },
            { "value": '[{"field":"eps_g_5y", "type":"<", "value":0.20}]', 'text': 'Under 20%' },
            { "value": '[{"field":"eps_g_5y", "type":"<", "value":0.15}]', 'text': 'Under 15%' },
            { "value": '[{"field":"eps_g_5y", "type":"<", "value":0.10}]', 'text': 'Under 10%' },
            { "value": '[{"field":"eps_g_5y", "type":"<", "value":0.05}]', 'text': 'Under 5%' },
            { "value": '[{"field":"eps_g_5y", "type":"<", "value":0.03}]', 'text': 'Under 3%' },
            { "value": '[{"field":"eps_g_5y", "type":"<", "value":0.02}]', 'text': 'Under 2%' }]
    },
    {
        "name": "filter-revenue-g-1y", "filters": [
            { "value": '[{"field":"revenue_g_1y", "type":"<", "value":0}]', 'text': 'Negative (< 0%)' },
            { "value": '[{"field":"revenue_g_1y", "type":">", "value":0}]', 'text': 'Positive (> 0%)' },
            { "value": '[{"field":"revenue_g_1y", "type":">", "value":0.01}, {"field":"revenue_g_1y", "type":"<=", "value":0.01}]', 'text': 'Positive Low (1% - 10%)' },
            { "value": '[{"field":"revenue_g_1y", "type":">", "value":0.2}]', 'text': 'High (>20%)' },
            { "value": '[{"field":"revenue_g_1y", "type":">", "value":0.30}]', 'text': 'Over 30% ' },
            { "value": '[{"field":"revenue_g_1y", "type":">", "value":0.25}]', 'text': 'Over 25%' },
            { "value": '[{"field":"revenue_g_1y", "type":">", "value":0.20}]', 'text': 'Over 20%' },
            { "value": '[{"field":"revenue_g_1y", "type":">", "value":0.15}]', 'text': 'Over 15%' },
            { "value": '[{"field":"revenue_g_1y", "type":">", "value":0.10}]', 'text': 'Over 10%' },
            { "value": '[{"field":"revenue_g_1y", "type":">", "value":0.05}]', 'text': 'Over 5%' },
            { "value": '[{"field":"revenue_g_1y", "type":">", "value":0.03}]', 'text': 'Over 3%' },
            { "value": '[{"field":"revenue_g_1y", "type":">", "value":0.02}]', 'text': 'Over 2%' },
            { "value": '[{"field":"revenue_g_1y", "type":"<", "value":0.30}]', 'text': 'Under 30%' },
            { "value": '[{"field":"revenue_g_1y", "type":"<", "value":0.25}]', 'text': 'Under 25%' },
            { "value": '[{"field":"revenue_g_1y", "type":"<", "value":0.20}]', 'text': 'Under 20%' },
            { "value": '[{"field":"revenue_g_1y", "type":"<", "value":0.15}]', 'text': 'Under 15%' },
            { "value": '[{"field":"revenue_g_1y", "type":"<", "value":0.10}]', 'text': 'Under 10%' },
            { "value": '[{"field":"revenue_g_1y", "type":"<", "value":0.05}]', 'text': 'Under 5%' },
            { "value": '[{"field":"revenue_g_1y", "type":"<", "value":0.03}]', 'text': 'Under 3%' },
            { "value": '[{"field":"revenue_g_1y", "type":"<", "value":0.02}]', 'text': 'Under 2%' }]
    }

    , {
        "name": "filter-roi", "filters": [
            { "value": '[{"field":"ROI", "type":"<", "value":0}]', 'text': 'Negative (< 0%)' },
            { "value": '[{"field":"ROI", "type":">", "value":0}]', 'text': 'Positive (> 0%)' },
            { "value": '[{"field":"ROI", "type":">", "value":-0.3}]', 'text': 'Very Low (< -30%)' },
            { "value": '[{"field":"ROI", "type":">", "value":0.25}]', 'text': 'High (> 25%)' },
            { "value": '[{"field":"ROI", "type":">", "value":0.30}]', 'text': 'Over +30% ' },
            { "value": '[{"field":"ROI", "type":">", "value":0.25}]', 'text': 'Over +25%' },
            { "value": '[{"field":"ROI", "type":">", "value":0.20}]', 'text': 'Over +20%' },
            { "value": '[{"field":"ROI", "type":">", "value":0.15}]', 'text': 'Over +15%' },
            { "value": '[{"field":"ROI", "type":">", "value":0.10}]', 'text': 'Over +10%' },
            { "value": '[{"field":"ROI", "type":">", "value":0.05}]', 'text': 'Over +5%' },
            { "value": '[{"field":"ROI", "type":">", "value":0.03}]', 'text': 'Over +3%' },
            { "value": '[{"field":"ROI", "type":">", "value":0.02}]', 'text': 'Over +2%' },
            { "value": '[{"field":"ROI", "type":"<", "value":-0.30}]', 'text': 'Under -30%' },
            { "value": '[{"field":"ROI", "type":"<", "value":-0.25}]', 'text': 'Under -25%' },
            { "value": '[{"field":"ROI", "type":"<", "value":-0.20}]', 'text': 'Under -20%' },
            { "value": '[{"field":"ROI", "type":"<", "value":-0.15}]', 'text': 'Under -15%' },
            { "value": '[{"field":"ROI", "type":"<", "value":-0.10}]', 'text': 'Under -10%' },
            { "value": '[{"field":"ROI", "type":"<", "value":-0.05}]', 'text': 'Under -5%' },
            { "value": '[{"field":"ROI", "type":"<", "value":-0.03}]', 'text': 'Under -3%' },
            { "value": '[{"field":"ROI", "type":"<", "value":-0.02}]', 'text': 'Under -2%' }]
    }

    , {
        "name": "filter-roa", "filters": [
            { "value": '[{"field":"ROA", "type":"<", "value":0}]', 'text': 'Negative (< 0%)' },
            { "value": '[{"field":"ROA", "type":">", "value":0}]', 'text': 'Positive (> 0%)' },
            { "value": '[{"field":"ROA", "type":">", "value":-0.3}]', 'text': 'Very Low (< -30%)' },
            { "value": '[{"field":"ROA", "type":">", "value":0.25}]', 'text': 'High (> 25%)' },
            { "value": '[{"field":"ROA", "type":">", "value":0.30}]', 'text': 'Over +30% ' },
            { "value": '[{"field":"ROA", "type":">", "value":0.25}]', 'text': 'Over +25%' },
            { "value": '[{"field":"ROA", "type":">", "value":0.20}]', 'text': 'Over +20%' },
            { "value": '[{"field":"ROA", "type":">", "value":0.15}]', 'text': 'Over +15%' },
            { "value": '[{"field":"ROA", "type":">", "value":0.10}]', 'text': 'Over +10%' },
            { "value": '[{"field":"ROA", "type":">", "value":0.05}]', 'text': 'Over +5%' },
            { "value": '[{"field":"ROA", "type":">", "value":0.03}]', 'text': 'Over +3%' },
            { "value": '[{"field":"ROA", "type":">", "value":0.02}]', 'text': 'Over +2%' },
            { "value": '[{"field":"ROA", "type":"<", "value":-0.30}]', 'text': 'Under -30%' },
            { "value": '[{"field":"ROA", "type":"<", "value":-0.25}]', 'text': 'Under -25%' },
            { "value": '[{"field":"ROA", "type":"<", "value":-0.20}]', 'text': 'Under -20%' },
            { "value": '[{"field":"ROA", "type":"<", "value":-0.15}]', 'text': 'Under -15%' },
            { "value": '[{"field":"ROA", "type":"<", "value":-0.10}]', 'text': 'Under -10%' },
            { "value": '[{"field":"ROA", "type":"<", "value":-0.05}]', 'text': 'Under -5%' },
            { "value": '[{"field":"ROA", "type":"<", "value":-0.03}]', 'text': 'Under -3%' },
            { "value": '[{"field":"ROA", "type":"<", "value":-0.02}]', 'text': 'Under -2%' }]
    }

    , {
        "name": "filter-cr", "filters": [
            { "value": '[{"field":"current_ratio", "type":">", "value":8}]', 'text': 'Over 8' },
            { "value": '[{"field":"current_ratio", "type":">", "value":5}]', 'text': 'Over 5' },
            { "value": '[{"field":"current_ratio", "type":">", "value":3}]', 'text': 'Over 3' },
            { "value": '[{"field":"current_ratio", "type":">", "value":2}]', 'text': 'Over 2' },
            { "value": '[{"field":"current_ratio", "type":">", "value":1}]', 'text': 'Over 1' },
            { "value": '[{"field":"current_ratio", "type":"<", "value":3}]', 'text': 'Less than 3' },
            { "value": '[{"field":"current_ratio", "type":"<", "value":2}]', 'text': 'Less than 2' },
            { "value": '[{"field":"current_ratio", "type":"<", "value":1}]', 'text': 'Less than 1' },
            { "value": '[{"field":"current_ratio", "type":"<", "value":0.5}]', 'text': 'Less than 0.5' }]
    }
    , {
        "name": "filter-lt-debt-equity", "filters": [
            { "value": '[{"field":"lt_debt_equity", "type":"<", "value":1}]', 'text': 'Over 1' },
            { "value": '[{"field":"lt_debt_equity", "type":">", "value":0.9}]', 'text': 'Over 0.9' },
            { "value": '[{"field":"lt_debt_equity", "type":">", "value":0.8}]', 'text': 'Over 0.8' },
            { "value": '[{"field":"lt_debt_equity", "type":">", "value":0.7}]', 'text': 'Over 0.7' },
            { "value": '[{"field":"lt_debt_equity", "type":">", "value":0.5}]', 'text': 'Over 0.5' },
            { "value": '[{"field":"lt_debt_equity", "type":">", "value":0.4}]', 'text': 'Over 0.4 ' },
            { "value": '[{"field":"lt_debt_equity", "type":">", "value":0.3}]', 'text': 'Over 0.3' },
            { "value": '[{"field":"lt_debt_equity", "type":">", "value":0.2}]', 'text': 'Over 0.2' },
            { "value": '[{"field":"lt_debt_equity", "type":">", "value":0.1}]', 'text': 'Over 0.1' },
            { "value": '[{"field":"lt_debt_equity", "type":"<", "value":0.1}]', 'text': 'Under 0.1' },
            { "value": '[{"field":"lt_debt_equity", "type":"<", "value":0.2}]', 'text': 'Under 0.2' },
            { "value": '[{"field":"lt_debt_equity", "type":"<", "value":0.3}]', 'text': 'Under 0.3' },
            { "value": '[{"field":"lt_debt_equity", "type":"<", "value":0.4}]', 'text': 'Under 0.4' },
            { "value": '[{"field":"lt_debt_equity", "type":"<", "value":0.5}]', 'text': 'Under 0.5' },
            { "value": '[{"field":"lt_debt_equity", "type":"<", "value":0.8}]', 'text': 'Under 0.8' },
            { "value": '[{"field":"lt_debt_equity", "type":"<", "value":0.9}]', 'text': 'Under 0.9' },
            { "value": '[{"field":"lt_debt_equity", "type":"<", "value":1}]', 'text': 'Under 1' }]
    },
    // {
    //     "name": "filter-cr", "filters": [
    //         { "value": '[{"field":"CR", "type":"<", "value":1}]', 'text': 'Over 1' },
    //         { "value": '[{"field":"CR", "type":">", "value":0.9}]', 'text': 'Over 0.9' },
    //         { "value": '[{"field":"CR", "type":">", "value":0.8}]', 'text': 'Over 0.8' },
    //         { "value": '[{"field":"CR", "type":">", "value":0.7}]', 'text': 'Over 0.7' },
    //         { "value": '[{"field":"CR", "type":">", "value":0.5}]', 'text': 'Over 0.5' },
    //         { "value": '[{"field":"CR", "type":">", "value":0.4}]', 'text': 'Over 0.4 ' },
    //         { "value": '[{"field":"CR", "type":">", "value":0.3}]', 'text': 'Over 0.3' },
    //         { "value": '[{"field":"CR", "type":">", "value":0.2}]', 'text': 'Over 0.2' },
    //         { "value": '[{"field":"CR", "type":">", "value":0.1}]', 'text': 'Over 0.1' },
    //         { "value": '[{"field":"CR", "type":"<", "value":0.1}]', 'text': 'Under 0.1' },
    //         { "value": '[{"field":"CR", "type":"<", "value":0.2}]', 'text': 'Under 0.2' },
    //         { "value": '[{"field":"CR", "type":"<", "value":0.3}]', 'text': 'Under 0.3' },
    //         { "value": '[{"field":"CR", "type":"<", "value":0.4}]', 'text': 'Under 0.4' },
    //         { "value": '[{"field":"CR", "type":"<", "value":0.5}]', 'text': 'Under 0.5' },
    //         { "value": '[{"field":"CR", "type":"<", "value":0.8}]', 'text': 'Under 0.8' },
    //         { "value": '[{"field":"CR", "type":"<", "value":0.9}]', 'text': 'Under 0.9' },
    //         { "value": '[{"field":"CR", "type":"<", "value":1}]', 'text': 'Under 1' }]
    // }
    , {
        "name": "filter-debt-equity", "filters": [
            { "value": '[{"field":"debt_equity_ratio", "type":"<", "value":1}]', 'text': 'Over 1' },
            { "value": '[{"field":"debt_equity_ratio", "type":">", "value":0.9}]', 'text': 'Over 0.9' },
            { "value": '[{"field":"debt_equity_ratio", "type":">", "value":0.8}]', 'text': 'Over 0.8' },
            { "value": '[{"field":"debt_equity_ratio", "type":">", "value":0.7}]', 'text': 'Over 0.7' },
            { "value": '[{"field":"debt_equity_ratio", "type":">", "value":0.5}]', 'text': 'Over 0.5' },
            { "value": '[{"field":"debt_equity_ratio", "type":">", "value":0.4}]', 'text': 'Over 0.4 ' },
            { "value": '[{"field":"debt_equity_ratio", "type":">", "value":0.3}]', 'text': 'Over 0.3' },
            { "value": '[{"field":"debt_equity_ratio", "type":">", "value":0.2}]', 'text': 'Over 0.2' },
            { "value": '[{"field":"debt_equity_ratio", "type":">", "value":0.1}]', 'text': 'Over 0.1' },
            { "value": '[{"field":"debt_equity_ratio", "type":"<", "value":0.1}]', 'text': 'Under 0.1' },
            { "value": '[{"field":"debt_equity_ratio", "type":"<", "value":0.2}]', 'text': 'Under 0.2' },
            { "value": '[{"field":"debt_equity_ratio", "type":"<", "value":0.3}]', 'text': 'Under 0.3' },
            { "value": '[{"field":"debt_equity_ratio", "type":"<", "value":0.4}]', 'text': 'Under 0.4' },
            { "value": '[{"field":"debt_equity_ratio", "type":"<", "value":0.5}]', 'text': 'Under 0.5' },
            { "value": '[{"field":"debt_equity_ratio", "type":"<", "value":0.8}]', 'text': 'Under 0.8' },
            { "value": '[{"field":"debt_equity_ratio", "type":"<", "value":0.9}]', 'text': 'Under 0.9' },
            { "value": '[{"field":"debt_equity_ratio", "type":"<", "value":1}]', 'text': 'Under 1' }]
    }

    , {
        "name": "filter-gm", "filters": [
            { "value": '[{"field":"GM", "type":"<", "value":0}]', 'text': 'Negative (< 0%)' },
            { "value": '[{"field":"GM", "type":">", "value":0}]', 'text': 'Positive (> 0%)' },
            { "value": '[{"field":"GM", "type":">", "value":1}]', 'text': 'Over +100%' },
            { "value": '[{"field":"GM", "type":">", "value":0.85}]', 'text': 'Over +85%' },
            { "value": '[{"field":"GM", "type":">", "value":0.50}]', 'text': 'Over +50% ' },
            { "value": '[{"field":"GM", "type":">", "value":0.25}]', 'text': 'Over +25%' },
            { "value": '[{"field":"GM", "type":">", "value":0.20}]', 'text': 'Over +20%' },
            { "value": '[{"field":"GM", "type":">", "value":0.15}]', 'text': 'Over +15%' },
            { "value": '[{"field":"GM", "type":">", "value":0.10}]', 'text': 'Over +10%' },
            { "value": '[{"field":"GM", "type":">", "value":0.05}]', 'text': 'Over +5%' },
            { "value": '[{"field":"GM", "type":">", "value":0.03}]', 'text': 'Over +3%' },
            { "value": '[{"field":"GM", "type":">", "value":0.02}]', 'text': 'Over +2%' },
            { "value": '[{"field":"GM", "type":"<", "value":0.80}]', 'text': 'Under +85%' },
            { "value": '[{"field":"GM", "type":"<", "value":0.50}]', 'text': 'Under +50%' },
            { "value": '[{"field":"GM", "type":"<", "value":0.20}]', 'text': 'Under +20%' },
            { "value": '[{"field":"GM", "type":"<", "value":0.15}]', 'text': 'Under +15%' },
            { "value": '[{"field":"GM", "type":"<", "value":0.10}]', 'text': 'Under +10%' },
            { "value": '[{"field":"GM", "type":"<", "value":0.05}]', 'text': 'Under +5%' },
            { "value": '[{"field":"GM", "type":"<", "value":0.03}]', 'text': 'Under +3%' },
            { "value": '[{"field":"GM", "type":"<", "value":0.02}]', 'text': 'Under +2%' },
            { "value": '[{"field":"GM", "type":"<", "value":0.01}]', 'text': 'Under +1%' },
            { "value": '[{"field":"GM", "type":"<", "value":-0.85}]', 'text': 'Under -85%' },
            { "value": '[{"field":"GM", "type":"<", "value":-0.50}]', 'text': 'Under -50%' },
            { "value": '[{"field":"GM", "type":"<", "value":-0.20}]', 'text': 'Under -20%' },
            { "value": '[{"field":"GM", "type":"<", "value":-0.15}]', 'text': 'Under -15%' },
            { "value": '[{"field":"GM", "type":"<", "value":-0.10}]', 'text': 'Under -10%' },
            { "value": '[{"field":"GM", "type":"<", "value":-0.05}]', 'text': 'Under -5%' },
            { "value": '[{"field":"GM", "type":"<", "value":-0.03}]', 'text': 'Under -3%' },
            { "value": '[{"field":"GM", "type":"<", "value":-0.02}]', 'text': 'Under -2%' }]
    }

    , {
        "name": "filter-om", "filters": [
            { "value": '[{"field":"OM", "type":"<", "value":0}]', 'text': 'Negative (< 0%)' },
            { "value": '[{"field":"OM", "type":">", "value":0}]', 'text': 'Positive (> 0%)' },
            { "value": '[{"field":"OM", "type":">", "value":1}]', 'text': 'Over +100%' },
            { "value": '[{"field":"OM", "type":">", "value":0.85}]', 'text': 'Over +85%' },
            { "value": '[{"field":"OM", "type":">", "value":0.50}]', 'text': 'Over +50% ' },
            { "value": '[{"field":"OM", "type":">", "value":0.25}]', 'text': 'Over +25%' },
            { "value": '[{"field":"OM", "type":">", "value":0.20}]', 'text': 'Over +20%' },
            { "value": '[{"field":"OM", "type":">", "value":0.15}]', 'text': 'Over +15%' },
            { "value": '[{"field":"OM", "type":">", "value":0.10}]', 'text': 'Over +10%' },
            { "value": '[{"field":"OM", "type":">", "value":0.05}]', 'text': 'Over +5%' },
            { "value": '[{"field":"OM", "type":">", "value":0.03}]', 'text': 'Over +3%' },
            { "value": '[{"field":"OM", "type":">", "value":0.02}]', 'text': 'Over +2%' },
            { "value": '[{"field":"OM", "type":"<", "value":0.80}]', 'text': 'Under +85%' },
            { "value": '[{"field":"OM", "type":"<", "value":0.50}]', 'text': 'Under +50%' },
            { "value": '[{"field":"OM", "type":"<", "value":0.20}]', 'text': 'Under +20%' },
            { "value": '[{"field":"OM", "type":"<", "value":0.15}]', 'text': 'Under +15%' },
            { "value": '[{"field":"OM", "type":"<", "value":0.10}]', 'text': 'Under +10%' },
            { "value": '[{"field":"OM", "type":"<", "value":0.05}]', 'text': 'Under +5%' },
            { "value": '[{"field":"OM", "type":"<", "value":0.03}]', 'text': 'Under +3%' },
            { "value": '[{"field":"OM", "type":"<", "value":0.02}]', 'text': 'Under +2%' },
            { "value": '[{"field":"OM", "type":"<", "value":0.01}]', 'text': 'Under +1%' },
            { "value": '[{"field":"OM", "type":"<", "value":-0.85}]', 'text': 'Under -85%' },
            { "value": '[{"field":"OM", "type":"<", "value":-0.50}]', 'text': 'Under -50%' },
            { "value": '[{"field":"OM", "type":"<", "value":-0.20}]', 'text': 'Under -20%' },
            { "value": '[{"field":"OM", "type":"<", "value":-0.15}]', 'text': 'Under -15%' },
            { "value": '[{"field":"OM", "type":"<", "value":-0.10}]', 'text': 'Under -10%' },
            { "value": '[{"field":"OM", "type":"<", "value":-0.05}]', 'text': 'Under -5%' },
            { "value": '[{"field":"OM", "type":"<", "value":-0.03}]', 'text': 'Under -3%' },
            { "value": '[{"field":"OM", "type":"<", "value":-0.02}]', 'text': 'Under -2%' }]
    },
    {
        "name": "filter-pm", "filters": [
            { "value": '[{"field":"PM", "type":"<", "value":0}]', 'text': 'Negative (< 0%)' },
            { "value": '[{"field":"PM", "type":">", "value":0}]', 'text': 'Positive (> 0%)' },
            { "value": '[{"field":"PM", "type":">", "value":1}]', 'text': 'Over +100%' },
            { "value": '[{"field":"PM", "type":">", "value":0.85}]', 'text': 'Over +85%' },
            { "value": '[{"field":"PM", "type":">", "value":0.50}]', 'text': 'Over +50% ' },
            { "value": '[{"field":"PM", "type":">", "value":0.25}]', 'text': 'Over +25%' },
            { "value": '[{"field":"PM", "type":">", "value":0.20}]', 'text': 'Over +20%' },
            { "value": '[{"field":"PM", "type":">", "value":0.15}]', 'text': 'Over +15%' },
            { "value": '[{"field":"PM", "type":">", "value":0.10}]', 'text': 'Over +10%' },
            { "value": '[{"field":"PM", "type":">", "value":0.05}]', 'text': 'Over +5%' },
            { "value": '[{"field":"PM", "type":">", "value":0.03}]', 'text': 'Over +3%' },
            { "value": '[{"field":"PM", "type":">", "value":0.02}]', 'text': 'Over +2%' },
            { "value": '[{"field":"PM", "type":"<", "value":0.80}]', 'text': 'Under +85%' },
            { "value": '[{"field":"PM", "type":"<", "value":0.50}]', 'text': 'Under +50%' },
            { "value": '[{"field":"PM", "type":"<", "value":0.20}]', 'text': 'Under +20%' },
            { "value": '[{"field":"PM", "type":"<", "value":0.15}]', 'text': 'Under +15%' },
            { "value": '[{"field":"PM", "type":"<", "value":0.10}]', 'text': 'Under +10%' },
            { "value": '[{"field":"PM", "type":"<", "value":0.05}]', 'text': 'Under +5%' },
            { "value": '[{"field":"PM", "type":"<", "value":0.03}]', 'text': 'Under +3%' },
            { "value": '[{"field":"PM", "type":"<", "value":0.02}]', 'text': 'Under +2%' },
            { "value": '[{"field":"PM", "type":"<", "value":0.01}]', 'text': 'Under +1%' },
            { "value": '[{"field":"PM", "type":"<", "value":-0.85}]', 'text': 'Under -85%' },
            { "value": '[{"field":"PM", "type":"<", "value":-0.50}]', 'text': 'Under -50%' },
            { "value": '[{"field":"PM", "type":"<", "value":-0.20}]', 'text': 'Under -20%' },
            { "value": '[{"field":"PM", "type":"<", "value":-0.15}]', 'text': 'Under -15%' },
            { "value": '[{"field":"PM", "type":"<", "value":-0.10}]', 'text': 'Under -10%' },
            { "value": '[{"field":"PM", "type":"<", "value":-0.05}]', 'text': 'Under -5%' },
            { "value": '[{"field":"PM", "type":"<", "value":-0.03}]', 'text': 'Under -3%' },
            { "value": '[{"field":"PM", "type":"<", "value":-0.02}]', 'text': 'Under -2%' }]
    },
    {
        "name": "filter-roe", "filters": [
            { "value": '[{"field":"ROE", "type":"<", "value":0}]', 'text': 'Negative (< 0%)' },
            { "value": '[{"field":"ROE", "type":">", "value":0}]', 'text': 'Positive (> 0%)' },
            { "value": '[{"field":"ROE", "type":">", "value":-0.3}]', 'text': 'Very Low (< -30%)' },
            { "value": '[{"field":"ROE", "type":">", "value":0.25}]', 'text': 'High (> 25%)' },
            { "value": '[{"field":"ROE", "type":">", "value":0.30}]', 'text': 'Over +30% ' },
            { "value": '[{"field":"ROE", "type":">", "value":0.25}]', 'text': 'Over +25%' },
            { "value": '[{"field":"ROE", "type":">", "value":0.20}]', 'text': 'Over +20%' },
            { "value": '[{"field":"ROE", "type":">", "value":0.15}]', 'text': 'Over +15%' },
            { "value": '[{"field":"ROE", "type":">", "value":0.10}]', 'text': 'Over +10%' },
            { "value": '[{"field":"ROE", "type":">", "value":0.05}]', 'text': 'Over +5%' },
            { "value": '[{"field":"ROE", "type":">", "value":0.03}]', 'text': 'Over +3%' },
            { "value": '[{"field":"ROE", "type":">", "value":0.02}]', 'text': 'Over +2%' },
            { "value": '[{"field":"ROE", "type":"<", "value":-0.30}]', 'text': 'Under -30%' },
            { "value": '[{"field":"ROE", "type":"<", "value":-0.25}]', 'text': 'Under -25%' },
            { "value": '[{"field":"ROE", "type":"<", "value":-0.20}]', 'text': 'Under -20%' },
            { "value": '[{"field":"ROE", "type":"<", "value":-0.15}]', 'text': 'Under -15%' },
            { "value": '[{"field":"ROE", "type":"<", "value":-0.10}]', 'text': 'Under -10%' },
            { "value": '[{"field":"ROE", "type":"<", "value":-0.05}]', 'text': 'Under -5%' },
            { "value": '[{"field":"ROE", "type":"<", "value":-0.03}]', 'text': 'Under -3%' },
            { "value": '[{"field":"ROE", "type":"<", "value":-0.02}]', 'text': 'Under -2%' }]
    }

    , {
        "name": "filter-inst-own", "filters": [
            { "value": '[{"field":"institutional_own", "type":">", "value":90}]', 'text': 'High (>90%)' },
            { "value": '[{"field":"institutional_own", "type":">", "value":80}]', 'text': 'Over 80% ' },
            { "value": '[{"field":"institutional_own", "type":">", "value":65}]', 'text': 'Over 65%' },
            { "value": '[{"field":"institutional_own", "type":">", "value":50}]', 'text': 'Over 50%' },
            { "value": '[{"field":"institutional_own", "type":">", "value":25}]', 'text': 'Over 25%' },
            { "value": '[{"field":"institutional_own", "type":">", "value":15}]', 'text': 'Over 15%' },
            { "value": '[{"field":"institutional_own", "type":">", "value":10}]', 'text': 'Over 10%' },
            { "value": '[{"field":"institutional_own", "type":">", "value":5}]', 'text': 'Over 5%' },
            { "value": '[{"field":"institutional_own", "type":">", "value":1}]', 'text': 'Over 1%' },
            { "value": '[{"field":"institutional_own", "type":"<", "value":90}]', 'text': 'Under 90%' },
            { "value": '[{"field":"institutional_own", "type":"<", "value":80}]', 'text': 'Under 80%' },
            { "value": '[{"field":"institutional_own", "type":"<", "value":50}]', 'text': 'Under 50%' },
            { "value": '[{"field":"institutional_own", "type":"<", "value":25}]', 'text': 'Under 25%' },
            { "value": '[{"field":"institutional_own", "type":"<", "value":15}]', 'text': 'Under 15%' },
            { "value": '[{"field":"institutional_own", "type":"<", "value":10}]', 'text': 'Under 10%' },
            { "value": '[{"field":"institutional_own", "type":"<", "value":5}]', 'text': 'Under 5%' },
            { "value": '[{"field":"institutional_own", "type":"<", "value":1}]', 'text': 'Under 1%' }]
    }
]

// , debt_equity_filters = { "name" : "", "filters" : [
// { "value" :  '[{"field":"debt_equity", "type":"<", "value":1}]', 'text': 'Over 1'},
// { "value" :  '[{"field":"debt_equity", "type":">", "value":0.9}]', 'text': 'Over 0.9'},
// { "value" :  '[{"field":"debt_equity", "type":">", "value":0.8}]', 'text': 'Over 0.8'},
// { "value" :  '[{"field":"debt_equity", "type":">", "value":0.7}]', 'text': 'Over 0.7'},
// { "value" :  '[{"field":"debt_equity", "type":">", "value":0.5}]', 'text': 'Over 0.5'},
// { "value" :  '[{"field":"debt_equity", "type":">", "value":0.4}]', 'text': 'Over 0.4 '},
// { "value" :  '[{"field":"debt_equity", "type":">", "value":0.3}]', 'text': 'Over 0.3'},
// { "value" :  '[{"field":"debt_equity", "type":">", "value":0.2}]', 'text': 'Over 0.2'},
// { "value" :  '[{"field":"debt_equity", "type":">", "value":0.1}]', 'text': 'Over 0.1'},
// { "value" :  '[{"field":"debt_equity", "type":"<", "value":0.1}]', 'text': 'Under 0.1'},
// { "value" :  '[{"field":"debt_equity", "type":"<", "value":0.2}]', 'text': 'Under 0.2'},
// { "value" :  '[{"field":"debt_equity", "type":"<", "value":0.3}]', 'text': 'Under 0.3'},
// { "value" :  '[{"field":"debt_equity", "type":"<", "value":0.4}]', 'text': 'Under 0.4'},
// { "value" :  '[{"field":"debt_equity", "type":"<", "value":0.5}]', 'text': 'Under 0.5'},
// { "value" :  '[{"field":"debt_equity", "type":"<", "value":0.8}]', 'text': 'Under 0.8'},
// { "value" :  '[{"field":"debt_equity", "type":"<", "value":0.9}]', 'text': 'Under 0.9'},
// { "value" :  '[{"field":"debt_equity", "type":"<", "value":1}]', 'text': 'Under 1'}]}


/**
{ "value" :  '[{"field":"avg_volume","type":">=","value":1000000}]', 'text': '&gt;= 2018'},
{ "value" :  '[{"field":"ipo_date","type":">=","value":"01-01-2015"},{"field":"ipo_date","type":"<=","value":"31-12-2017"}]', 'text': '2015 - 2017'},
{ "value" :  '[{"field":"ipo_date","type":">=","value":"01-01-2012"},{"field":"ipo_date","type":"<=","value":"31-12-2014"}]', 'text': '2012 - 2014 '},
{ "value" :  '[{"field":"ipo_date","type":">=","value":"01-01-2009"},{"field":"ipo_date","type":"<=","value":"31-12-2011"}]', 'text': '2009 - 2011'},
{ "value" :  '[{"field":"ipo_date","type":">=","value":"01-01-2006"},{"field":"ipo_date","type":"<=","value":"31-12-2008"}]', 'text': '2006 - 2008'},
{ "value" :  '[{"field":"ipo_date","type":">=","value":"01-01-2003"},{"field":"ipo_date","type":"<=","value":"31-12-2005"}]', 'text': '2003 - 2005'},
{ "value" :  '[{"field":"ipo_date","type":">=","value":"01-01-2000"},{"field":"ipo_date","type":"<=","value":"31-12-2002"}]', 'text': '2000 - 2002'},
{ "value" :  '[{"field":"ipo_date","type":">=","value":"01-01-1997"},{"field":"ipo_date","type":"<=","value":"31-12-1999"}]', 'text': '1997 - 1999'},
{ "value" :  '[{"field":"ipo_date","type":">=","value":"01-01-1994"},{"field":"ipo_date","type":"<=","value":"31-12-1996"}]', 'text': '1994 - 1996'},
{ "value" :  '[{"field":"ipo_date","type":">=","value":"01-01-1991"},{"field":"ipo_date","type":"<=","value":"31-12-1993"}]', 'text': '1991 - 1993'},
{ "value" :  '[{"field":"ipo_date","type":">=","value":"31-12-1990"}]', 'text': '&lt;= 1990'},
},
{ "value" :  '[{"field":"sector","type":"=","value":"basic"}]', 'text': 'Basic Materials'},
{ "value" :  '[{"field":"sector","type":"=","value":"consumer"}]', 'text': 'Consumer Goods'},
{ "value" :  '[{"field":"sector","type":"=","value":"conglomerates"}]', 'text': 'Conglomerates'},
{ "value" :  '[{"field":"sector","type":"=","value":"financial"}]', 'text': 'Financial'},
{ "value" :  '[{"field":"sector","type":"=","value":"industrial"}]', 'text': 'Industrial Goods'},
{ "value" :  '[{"field":"sector","type":"=","value":"services"}]', 'text': 'Services'},
{ "value" :  '[{"field":"sector","type":"=","value":"technology"}]', 'text': 'Technology'},
{ "value" :  '[{"field":"sector","type":"=","value":"utilities"}]', 'text': 'Utilities'},
},
{ "value" :  '[{"field":"industry","type":"=","value":"asset_management"}]', 'text': 'Asset Management'},
{ "value" :  '[{"field":"industry","type":"=","value":"banking_retail"}]', 'text': 'Banking - Retail'},
{ "value" :  '[{"field":"industry","type":"=","value":"banking_investment"}]', 'text': 'Banking - Investment'},
{ "value" :  '[{"field":"industry","type":"=","value":"consumer_goods_retail"}]', 'text': 'Consumer Goods Retail'},
{ "value" :  '[{"field":"industry","type":"=","value":"manufacturing"}]', 'text': 'Consumer Goods Man.'},
{ "value" :  '[{"field":"industry","type":"=","value":"diversified_investments"}]', 'text': 'Diversified Investments'},
{ "value" :  '[{"field":"industry","type":"=","value":"hotel_management}]', 'text': 'Hotel Management'},
{ "value" :  '[{"field":"industry","type":"=","value":"it_services"}]', 'text': 'IT Services'},
{ "value" :  '[{"field":"industry","type":"=","value":"insurance"}]', 'text': 'Insurance'},
{ "value" :  '[{"field":"industry","type":"=","value":"real_estate_development"}]', 'text': 'Real Estate Development'},
},
{ "value" :  '[{"field":"pe", "type":">", "value":5}]', 'text': 'Over 5'},
{ "value" :  '[{"field":"pe", "type":">", "value":10}]', 'text': 'Over 10'},
{ "value" :  '[{"field":"pe", "type":">", "value":15}]', 'text': 'Over 15'},
{ "value" :  '[{"field":"pe", "type":">", "value":20}]', 'text': 'Over 20'},
{ "value" :  '[{"field":"pe", "type":">", "value":25}]', 'text': 'Over 25'},
{ "value" :  '[{"field":"pe", "type":">", "value":30}]', 'text': 'Over 30'},
{ "value" :  '[{"field":"pe", "type":">", "value":35}]', 'text': 'Over 35'},
{ "value" :  '[{"field":"pe", "type":">", "value":50}]', 'text': 'Over 50'},
{ "value" :  '[{"field":"pe", "type":"<", "value":5}]', 'text': 'Less than 5'},
{ "value" :  '[{"field":"pe", "type":"<", "value":10}]', 'text': 'Less than 10'},
{ "value" :  '[{"field":"pe", "type":"<", "value":15}]', 'text': 'Less than 15'},
{ "value" :  '[{"field":"pe", "type":"<", "value":25}]', 'text': 'Less than 25'},
{ "value" :  '[{"field":"pe", "type":"<", "value":30}]', 'text': 'Less than 30'},
},
{ "value" :  '[{"field":"peg", "type":">", "value":3}]', 'text': 'Over 3'},
{ "value" :  '[{"field":"peg", "type":">", "value":2}]', 'text': 'Over 2'},
{ "value" :  '[{"field":"peg", "type":">=", "value":1}]', 'text': 'Over 1'},
{ "value" :  '[{"field":"peg", "type":"<=", "value":3}]', 'text': 'Less than 3'},
{ "value" :  '[{"field":"peg", "type":"<=", "value":2}]', 'text': 'Less than 2'},
{ "value" :  '[{"field":"peg", "type":"<=", "value":20}]', 'text': 'Less than 1'},
},
{ "value" :  '[{"field":"ps", "type":">", "value":10}]', 'text': 'Over 10'},
{ "value" :  '[{"field":"ps", "type":">", "value":8}]', 'text': 'Over 8'},
{ "value" :  '[{"field":"ps", "type":">", "value":6}]', 'text': 'Over 6'},
{ "value" :  '[{"field":"ps", "type":">", "value":5}]', 'text': 'Over 5'},
{ "value" :  '[{"field":"ps", "type":">", "value":4}]', 'text': 'Over 4'},
{ "value" :  '[{"field":"ps", "type":">", "value":3}]', 'text': 'Over 3'},
{ "value" :  '[{"field":"ps", "type":">", "value":2}]', 'text': 'Over 2'},
{ "value" :  '[{"field":"ps", "type":">", "value":1}]', 'text': 'Over 1'},
{ "value" :  '[{"field":"ps", "type":"<=", "value":10}]', 'text': 'Under 10'},
{ "value" :  '[{"field":"ps", "type":"<=", "value":8}]', 'text': 'Under 8'},
{ "value" :  '[{"field":"ps", "type":"<=", "value":6}]', 'text': 'Under 6'},
{ "value" :  '[{"field":"ps", "type":"<=", "value":5}]', 'text': 'Under 5'},
{ "value" :  '[{"field":"ps", "type":"<=", "value":4}]', 'text': 'Under 4'},
{ "value" :  '[{"field":"ps", "type":"<=", "value":3}]', 'text': 'Under 3'},
{ "value" :  '[{"field":"ps", "type":"<=", "value":2}]', 'text': 'Under 2'},
{ "value" :  '[{"field":"ps", "type":"<=", "value":1}]', 'text': 'Under 1'},
},
{ "value" :  '[{"field":"pbv", "type":">", "value":10}]', 'text': 'Over 10'},
{ "value" :  '[{"field":"pbv", "type":">", "value":8}]', 'text': 'Over 8'},
{ "value" :  '[{"field":"pbv", "type":">", "value":6}]', 'text': 'Over 6'},
{ "value" :  '[{"field":"pbv", "type":">", "value":5}]', 'text': 'Over 5'},
{ "value" :  '[{"field":"pbv", "type":">", "value":4}]', 'text': 'Over 4'},
{ "value" :  '[{"field":"pbv", "type":">", "value":3}]', 'text': 'Over 3'},
{ "value" :  '[{"field":"pbv", "type":">", "value":2}]', 'text': 'Over 2'},
{ "value" :  '[{"field":"pbv", "type":">", "value":1}]', 'text': 'Over 1'},
{ "value" :  '[{"field":"pbv", "type":"<=", "value":10}]', 'text': 'Under 10'},
{ "value" :  '[{"field":"pbv", "type":"<=", "value":8}]', 'text': 'Under 8'},
{ "value" :  '[{"field":"pbv", "type":"<=", "value":6}]', 'text': 'Under 6'},
{ "value" :  '[{"field":"pbv", "type":"<=", "value":5}]', 'text': 'Under 5'},
{ "value" :  '[{"field":"pbv", "type":"<=", "value":4}]', 'text': 'Under 4'},
{ "value" :  '[{"field":"pbv", "type":"<=", "value":3}]', 'text': 'Under 3'},
{ "value" :  '[{"field":"pbv", "type":"<=", "value":2}]', 'text': 'Under 2'},
{ "value" :  '[{"field":"pbv", "type":"<=", "value":1}]', 'text': 'Under 1'},
},
{ "value" :  '[{"field":"eps", "type":">", "value":30}]', 'text': 'Over 30'},
{ "value" :  '[{"field":"eps", "type":">", "value":25}]', 'text': 'Over 25'},
{ "value" :  '[{"field":"eps", "type":">", "value":10}]', 'text': 'Over 10'},
{ "value" :  '[{"field":"eps", "type":">", "value":5}]', 'text': 'Over 5'},
{ "value" :  '[{"field":"eps", "type":"<", "value":30}]', 'text': 'Below 30'},
{ "value" :  '[{"field":"eps", "type":"<", "value":20}]', 'text': 'Below 20'},
{ "value" :  '[{"field":"eps", "type":"<", "value":10}]', 'text': 'Below 10'},
{ "value" :  '[{"field":"eps", "type":"<", "value":5}]', 'text': 'Below 5'},
{ "value" :  '[{"field":"eps", "type":"<", "value":0}]', 'text': 'Negative (< 0)'},
},
{ "value" :  '[{"field":"eps_g_1y", "type":"<", "value":0}]', 'text': 'Negative (< 0%)'},
{ "value" :  '[{"field":"eps_g_1y", "type":">", "value":0}]', 'text': 'Positive (> 0%)'},
{ "value" :  '[{"field":"eps_g_1y", "type":">", "value":15}]', 'text': 'Positive Low (1% - 10%)'},
{ "value" :  '[{"field":"eps_g_1y", "type":">", "value":0.2}]', 'text': 'High (>20%)'},
{ "value" :  '[{"field":"eps_g_1y", "type":">", "value":0.25}]', 'text': 'Over 25%'},
{ "value" :  '[{"field":"eps_g_1y", "type":">", "value":0.20}]', 'text': 'Over 20%'},
{ "value" :  '[{"field":"eps_g_1y", "type":">", "value":0.15}]', 'text': 'Over 15%'},
{ "value" :  '[{"field":"eps_g_1y", "type":">", "value":0.10}]', 'text': 'Over 10%'},
{ "value" :  '[{"field":"eps_g_1y", "type":">", "value":0.05}]', 'text': 'Over 5%'},
{ "value" :  '[{"field":"eps_g_1y", "type":">", "value":0.03}]', 'text': 'Over 3%'},
{ "value" :  '[{"field":"eps_g_1y", "type":">", "value":0.02}]', 'text': 'Over 2%'},
{ "value" :  '[{"field":"eps_g_1y", "type":"<", "value":0.30}]', 'text': 'Under 30%'},
{ "value" :  '[{"field":"eps_g_1y", "type":"<", "value":0.25}]', 'text': 'Under 25%'},
{ "value" :  '[{"field":"eps_g_1y", "type":"<", "value":0.20}]', 'text': 'Under 20%'},
{ "value" :  '[{"field":"eps_g_1y", "type":"<", "value":0.15}]', 'text': 'Under 15%'},
{ "value" :  '[{"field":"eps_g_1y", "type":"<", "value":0.10}]', 'text': 'Under 10%'},
{ "value" :  '[{"field":"eps_g_1y", "type":"<", "value":0.05}]', 'text': 'Under 5%'},
{ "value" :  '[{"field":"eps_g_1y", "type":"<", "value":0.03}]', 'text': 'Under 3%'},
{ "value" :  '[{"field":"eps_g_1y", "type":"<", "value":0.02}]', 'text': 'Under 2%'},
},
{ "value" :  '[{"field":"eps_g_5y", "type":"<", "value":0}]', 'text': 'Negative (< 0%)'},
{ "value" :  '[{"field":"eps_g_5y", "type":">", "value":0}]', 'text': 'Positive (> 0%)'},
{ "value" :  '[{"field":"eps_g_5y", "type":">", "value":0.01}, {"field":"eps_g_5y", "type":"<=", "value":0.01}]', 'text': 'Positive Low (1% - 10%)'},
{ "value" :  '[{"field":"eps_g_5y", "type":">", "value":0.2}]', 'text': 'High (>20%)'},
{ "value" :  '[{"field":"eps_g_5y", "type":">", "value":0.30}]', 'text': 'Over 30% '},
{ "value" :  '[{"field":"eps_g_5y", "type":">", "value":0.25}]', 'text': 'Over 25%'},
{ "value" :  '[{"field":"eps_g_5y", "type":">", "value":0.20}]', 'text': 'Over 20%'},
{ "value" :  '[{"field":"eps_g_5y", "type":">", "value":0.15}]', 'text': 'Over 15%'},
{ "value" :  '[{"field":"eps_g_5y", "type":">", "value":0.10}]', 'text': 'Over 10%'},
{ "value" :  '[{"field":"eps_g_5y", "type":">", "value":0.05}]', 'text': 'Over 5%'},
{ "value" :  '[{"field":"eps_g_5y", "type":">", "value":0.03}]', 'text': 'Over 3%'},
{ "value" :  '[{"field":"eps_g_5y", "type":">", "value":0.02}]', 'text': 'Over 2%'},
{ "value" :  '[{"field":"eps_g_5y", "type":"<", "value":0.30}]', 'text': 'Under 30%'},
{ "value" :  '[{"field":"eps_g_5y", "type":"<", "value":0.25}]', 'text': 'Under 25%'},
{ "value" :  '[{"field":"eps_g_5y", "type":"<", "value":0.20}]', 'text': 'Under 20%'},
{ "value" :  '[{"field":"eps_g_5y", "type":"<", "value":0.15}]', 'text': 'Under 15%'},
{ "value" :  '[{"field":"eps_g_5y", "type":"<", "value":0.10}]', 'text': 'Under 10%'},
{ "value" :  '[{"field":"eps_g_5y", "type":"<", "value":0.05}]', 'text': 'Under 5%'},
{ "value" :  '[{"field":"eps_g_5y", "type":"<", "value":0.03}]', 'text': 'Under 3%'},
{ "value" :  '[{"field":"eps_g_5y", "type":"<", "value":0.02}]', 'text': 'Under 2%'},
},
{ "value" :  '[{"field":"roic", "type":"<", "value":0}]', 'text': 'Negative (< 0%)'},
{ "value" :  '[{"field":"roic", "type":">", "value":0}]', 'text': 'Positive (> 0%)'},
{ "value" :  '[{"field":"roic", "type":">", "value":-0.3}]', 'text': 'Very Low (< -30%)'},
{ "value" :  '[{"field":"roic", "type":">", "value":0.25}]', 'text': 'High (> 25%)'},
{ "value" :  '[{"field":"roic", "type":">", "value":0.30}]', 'text': 'Over +30% '},
{ "value" :  '[{"field":"roic", "type":">", "value":0.25}]', 'text': 'Over +25%'},
{ "value" :  '[{"field":"roic", "type":">", "value":0.20}]', 'text': 'Over +20%'},
{ "value" :  '[{"field":"roic", "type":">", "value":0.15}]', 'text': 'Over +15%'},
{ "value" :  '[{"field":"roic", "type":">", "value":0.10}]', 'text': 'Over +10%'},
{ "value" :  '[{"field":"roic", "type":">", "value":0.05}]', 'text': 'Over +5%'},
{ "value" :  '[{"field":"roic", "type":">", "value":0.03}]', 'text': 'Over +3%'},
{ "value" :  '[{"field":"roic", "type":">", "value":0.02}]', 'text': 'Over +2%'},
{ "value" :  '[{"field":"roic", "type":"<", "value":-0.30}]', 'text': 'Under -30%'},
{ "value" :  '[{"field":"roic", "type":"<", "value":-0.25}]', 'text': 'Under -25%'},
{ "value" :  '[{"field":"roic", "type":"<", "value":-0.20}]', 'text': 'Under -20%'},
{ "value" :  '[{"field":"roic", "type":"<", "value":-0.15}]', 'text': 'Under -15%'},
{ "value" :  '[{"field":"roic", "type":"<", "value":-0.10}]', 'text': 'Under -10%'},
{ "value" :  '[{"field":"roic", "type":"<", "value":-0.05}]', 'text': 'Under -5%'},
{ "value" :  '[{"field":"roic", "type":"<", "value":-0.03}]', 'text': 'Under -3%'},
{ "value" :  '[{"field":"roic", "type":"<", "value":-0.02}]', 'text': 'Under -2%'},
},
{ "value" :  '[{"field":"ROA", "type":"<", "value":0}]', 'text': 'Negative (< 0%)'},
{ "value" :  '[{"field":"ROA", "type":">", "value":0}]', 'text': 'Positive (> 0%)'},
{ "value" :  '[{"field":"ROA", "type":">", "value":-0.3}]', 'text': 'Very Low (< -30%)'},
{ "value" :  '[{"field":"ROA", "type":">", "value":0.25}]', 'text': 'High (> 25%)'},
{ "value" :  '[{"field":"ROA", "type":">", "value":0.30}]', 'text': 'Over +30% '},
{ "value" :  '[{"field":"ROA", "type":">", "value":0.25}]', 'text': 'Over +25%'},
{ "value" :  '[{"field":"ROA", "type":">", "value":0.20}]', 'text': 'Over +20%'},
{ "value" :  '[{"field":"ROA", "type":">", "value":0.15}]', 'text': 'Over +15%'},
{ "value" :  '[{"field":"ROA", "type":">", "value":0.10}]', 'text': 'Over +10%'},
{ "value" :  '[{"field":"ROA", "type":">", "value":0.05}]', 'text': 'Over +5%'},
{ "value" :  '[{"field":"ROA", "type":">", "value":0.03}]', 'text': 'Over +3%'},
{ "value" :  '[{"field":"ROA", "type":">", "value":0.02}]', 'text': 'Over +2%'},
{ "value" :  '[{"field":"ROA", "type":"<", "value":-0.30}]', 'text': 'Under -30%'},
{ "value" :  '[{"field":"ROA", "type":"<", "value":-0.25}]', 'text': 'Under -25%'},
{ "value" :  '[{"field":"ROA", "type":"<", "value":-0.20}]', 'text': 'Under -20%'},
{ "value" :  '[{"field":"ROA", "type":"<", "value":-0.15}]', 'text': 'Under -15%'},
{ "value" :  '[{"field":"ROA", "type":"<", "value":-0.10}]', 'text': 'Under -10%'},
{ "value" :  '[{"field":"ROA", "type":"<", "value":-0.05}]', 'text': 'Under -5%'},
{ "value" :  '[{"field":"ROA", "type":"<", "value":-0.03}]', 'text': 'Under -3%'},
{ "value" :  '[{"field":"ROA", "type":"<", "value":-0.02}]', 'text': 'Under -2%'},
},
{ "value" :  '[{"field":"current_ratio", "type":">", "value":8}]', 'text': 'Over 8'},
{ "value" :  '[{"field":"current_ratio", "type":">", "value":5}]', 'text': 'Over 5'},
{ "value" :  '[{"field":"current_ratio", "type":">", "value":3}]', 'text': 'Over 3'},
{ "value" :  '[{"field":"current_ratio", "type":">", "value":2}]', 'text': 'Over 2'},
{ "value" :  '[{"field":"current_ratio", "type":">", "value":1}]', 'text': 'Over 1'},
{ "value" :  '[{"field":"current_ratio", "type":"<", "value":3}]', 'text': 'Less than 3'},
{ "value" :  '[{"field":"current_ratio", "type":"<", "value":2}]', 'text': 'Less than 2'},
{ "value" :  '[{"field":"current_ratio", "type":"<", "value":1}]', 'text': 'Less than 1'},
{ "value" :  '[{"field":"current_ratio", "type":"<", "value":0.5}]', 'text': 'Less than 0.5'},
},
{ "value" :  '[{"field":"lt_debt_equity", "type":"<", "value":1}]', 'text': 'Over 1'},
{ "value" :  '[{"field":"lt_debt_equity", "type":">", "value":0.9}]', 'text': 'Over 0.9'},
{ "value" :  '[{"field":"lt_debt_equity", "type":">", "value":0.8}]', 'text': 'Over 0.8'},
{ "value" :  '[{"field":"lt_debt_equity", "type":">", "value":0.7}]', 'text': 'Over 0.7'},
{ "value" :  '[{"field":"lt_debt_equity", "type":">", "value":0.5}]', 'text': 'Over 0.5'},
{ "value" :  '[{"field":"lt_debt_equity", "type":">", "value":0.4}]', 'text': 'Over 0.4 '},
{ "value" :  '[{"field":"lt_debt_equity", "type":">", "value":0.3}]', 'text': 'Over 0.3'},
{ "value" :  '[{"field":"lt_debt_equity", "type":">", "value":0.2}]', 'text': 'Over 0.2'},
{ "value" :  '[{"field":"lt_debt_equity", "type":">", "value":0.1}]', 'text': 'Over 0.1'},
{ "value" :  '[{"field":"lt_debt_equity", "type":"<", "value":0.1}]', 'text': 'Under 0.1'},
{ "value" :  '[{"field":"lt_debt_equity", "type":"<", "value":0.2}]', 'text': 'Under 0.2'},
{ "value" :  '[{"field":"lt_debt_equity", "type":"<", "value":0.3}]', 'text': 'Under 0.3'},
{ "value" :  '[{"field":"lt_debt_equity", "type":"<", "value":0.4}]', 'text': 'Under 0.4'},
{ "value" :  '[{"field":"lt_debt_equity", "type":"<", "value":0.5}]', 'text': 'Under 0.5'},
{ "value" :  '[{"field":"lt_debt_equity", "type":"<", "value":0.8}]', 'text': 'Under 0.8'},
{ "value" :  '[{"field":"lt_debt_equity", "type":"<", "value":0.9}]', 'text': 'Under 0.9'},
{ "value" :  '[{"field":"lt_debt_equity", "type":"<", "value":1}]', 'text': 'Under 1'},
},
{ "value" :  '[{"field":"debt_equity", "type":"<", "value":1}]', 'text': 'Over 1'},
{ "value" :  '[{"field":"debt_equity", "type":">", "value":0.9}]', 'text': 'Over 0.9'},
{ "value" :  '[{"field":"debt_equity", "type":">", "value":0.8}]', 'text': 'Over 0.8'},
{ "value" :  '[{"field":"debt_equity", "type":">", "value":0.7}]', 'text': 'Over 0.7'},
{ "value" :  '[{"field":"debt_equity", "type":">", "value":0.5}]', 'text': 'Over 0.5'},
{ "value" :  '[{"field":"debt_equity", "type":">", "value":0.4}]', 'text': 'Over 0.4 '},
{ "value" :  '[{"field":"debt_equity", "type":">", "value":0.3}]', 'text': 'Over 0.3'},
{ "value" :  '[{"field":"debt_equity", "type":">", "value":0.2}]', 'text': 'Over 0.2'},
{ "value" :  '[{"field":"debt_equity", "type":">", "value":0.1}]', 'text': 'Over 0.1'},
{ "value" :  '[{"field":"debt_equity", "type":"<", "value":0.1}]', 'text': 'Under 0.1'},
{ "value" :  '[{"field":"debt_equity", "type":"<", "value":0.2}]', 'text': 'Under 0.2'},
{ "value" :  '[{"field":"debt_equity", "type":"<", "value":0.3}]', 'text': 'Under 0.3'},
{ "value" :  '[{"field":"debt_equity", "type":"<", "value":0.4}]', 'text': 'Under 0.4'},
{ "value" :  '[{"field":"debt_equity", "type":"<", "value":0.5}]', 'text': 'Under 0.5'},
{ "value" :  '[{"field":"debt_equity", "type":"<", "value":0.8}]', 'text': 'Under 0.8'},
{ "value" :  '[{"field":"debt_equity", "type":"<", "value":0.9}]', 'text': 'Under 0.9'},
{ "value" :  '[{"field":"debt_equity", "type":"<", "value":1}]', 'text': 'Under 1'},
},
{ "value" :  '[{"field":"GM", "type":"<", "value":0}]', 'text': 'Negative (< 0%)'},
{ "value" :  '[{"field":"GM", "type":">", "value":0}]', 'text': 'Positive (> 0%)'},
{ "value" :  '[{"field":"GM", "type":">", "value":1}]', 'text': 'Over +100%'},
{ "value" :  '[{"field":"GM", "type":">", "value":0.85}]', 'text': 'Over +85%'},
{ "value" :  '[{"field":"GM", "type":">", "value":0.50}]', 'text': 'Over +50% '},
{ "value" :  '[{"field":"GM", "type":">", "value":0.25}]', 'text': 'Over +25%'},
{ "value" :  '[{"field":"GM", "type":">", "value":0.20}]', 'text': 'Over +20%'},
{ "value" :  '[{"field":"GM", "type":">", "value":0.15}]', 'text': 'Over +15%'},
{ "value" :  '[{"field":"GM", "type":">", "value":0.10}]', 'text': 'Over +10%'},
{ "value" :  '[{"field":"GM", "type":">", "value":0.05}]', 'text': 'Over +5%'},
{ "value" :  '[{"field":"GM", "type":">", "value":0.03}]', 'text': 'Over +3%'},
{ "value" :  '[{"field":"GM", "type":">", "value":0.02}]', 'text': 'Over +2%'},
{ "value" :  '[{"field":"GM", "type":"<", "value":0.80}]', 'text': 'Under +85%'},
{ "value" :  '[{"field":"GM", "type":"<", "value":0.50}]', 'text': 'Under +50%'},
{ "value" :  '[{"field":"GM", "type":"<", "value":0.20}]', 'text': 'Under +20%'},
{ "value" :  '[{"field":"GM", "type":"<", "value":0.15}]', 'text': 'Under +15%'},
{ "value" :  '[{"field":"GM", "type":"<", "value":0.10}]', 'text': 'Under +10%'},
{ "value" :  '[{"field":"GM", "type":"<", "value":0.05}]', 'text': 'Under +5%'},
{ "value" :  '[{"field":"GM", "type":"<", "value":0.03}]', 'text': 'Under +3%'},
{ "value" :  '[{"field":"GM", "type":"<", "value":0.02}]', 'text': 'Under +2%'},
{ "value" :  '[{"field":"GM", "type":"<", "value":0.01}]', 'text': 'Under +1%'},
{ "value" :  '[{"field":"GM", "type":"<", "value":-0.85}]', 'text': 'Under -85%'},
{ "value" :  '[{"field":"GM", "type":"<", "value":-0.50}]', 'text': 'Under -50%'},
{ "value" :  '[{"field":"GM", "type":"<", "value":-0.20}]', 'text': 'Under -20%'},
{ "value" :  '[{"field":"GM", "type":"<", "value":-0.15}]', 'text': 'Under -15%'},
{ "value" :  '[{"field":"GM", "type":"<", "value":-0.10}]', 'text': 'Under -10%'},
{ "value" :  '[{"field":"GM", "type":"<", "value":-0.05}]', 'text': 'Under -5%'},
{ "value" :  '[{"field":"GM", "type":"<", "value":-0.03}]', 'text': 'Under -3%'},
{ "value" :  '[{"field":"GM", "type":"<", "value":-0.02}]', 'text': 'Under -2%'},
},
{ "value" :  '[{"field":"operating_margin", "type":"<", "value":0}]', 'text': 'Negative (< 0%)'},
{ "value" :  '[{"field":"operating_margin", "type":">", "value":0}]', 'text': 'Positive (> 0%)'},
{ "value" :  '[{"field":"operating_margin", "type":">", "value":1}]', 'text': 'Over +100%'},
{ "value" :  '[{"field":"operating_margin", "type":">", "value":0.85}]', 'text': 'Over +85%'},
{ "value" :  '[{"field":"operating_margin", "type":">", "value":0.50}]', 'text': 'Over +50% '},
{ "value" :  '[{"field":"operating_margin", "type":">", "value":0.25}]', 'text': 'Over +25%'},
{ "value" :  '[{"field":"operating_margin", "type":">", "value":0.20}]', 'text': 'Over +20%'},
{ "value" :  '[{"field":"operating_margin", "type":">", "value":0.15}]', 'text': 'Over +15%'},
{ "value" :  '[{"field":"operating_margin", "type":">", "value":0.10}]', 'text': 'Over +10%'},
{ "value" :  '[{"field":"operating_margin", "type":">", "value":0.05}]', 'text': 'Over +5%'},
{ "value" :  '[{"field":"operating_margin", "type":">", "value":0.03}]', 'text': 'Over +3%'},
{ "value" :  '[{"field":"operating_margin", "type":">", "value":0.02}]', 'text': 'Over +2%'},
{ "value" :  '[{"field":"operating_margin", "type":"<", "value":0.80}]', 'text': 'Under +85%'},
{ "value" :  '[{"field":"operating_margin", "type":"<", "value":0.50}]', 'text': 'Under +50%'},
{ "value" :  '[{"field":"operating_margin", "type":"<", "value":0.20}]', 'text': 'Under +20%'},
{ "value" :  '[{"field":"operating_margin", "type":"<", "value":0.15}]', 'text': 'Under +15%'},
{ "value" :  '[{"field":"operating_margin", "type":"<", "value":0.10}]', 'text': 'Under +10%'},
{ "value" :  '[{"field":"operating_margin", "type":"<", "value":0.05}]', 'text': 'Under +5%'},
{ "value" :  '[{"field":"operating_margin", "type":"<", "value":0.03}]', 'text': 'Under +3%'},
{ "value" :  '[{"field":"operating_margin", "type":"<", "value":0.02}]', 'text': 'Under +2%'},
{ "value" :  '[{"field":"operating_margin", "type":"<", "value":0.01}]', 'text': 'Under +1%'},
{ "value" :  '[{"field":"operating_margin", "type":"<", "value":-0.85}]', 'text': 'Under -85%'},
{ "value" :  '[{"field":"operating_margin", "type":"<", "value":-0.50}]', 'text': 'Under -50%'},
{ "value" :  '[{"field":"operating_margin", "type":"<", "value":-0.20}]', 'text': 'Under -20%'},
{ "value" :  '[{"field":"operating_margin", "type":"<", "value":-0.15}]', 'text': 'Under -15%'},
{ "value" :  '[{"field":"operating_margin", "type":"<", "value":-0.10}]', 'text': 'Under -10%'},
{ "value" :  '[{"field":"operating_margin", "type":"<", "value":-0.05}]', 'text': 'Under -5%'},
{ "value" :  '[{"field":"operating_margin", "type":"<", "value":-0.03}]', 'text': 'Under -3%'},
{ "value" :  '[{"field":"operating_margin", "type":"<", "value":-0.02}]', 'text': 'Under -2%'},
},
{ "value" :  '[{"field":"net_profit_margin", "type":"<", "value":0}]', 'text': 'Negative (< 0%)'},
{ "value" :  '[{"field":"net_profit_margin", "type":">", "value":0}]', 'text': 'Positive (> 0%)'},
{ "value" :  '[{"field":"net_profit_margin", "type":">", "value":1}]', 'text': 'Over +100%'},
{ "value" :  '[{"field":"net_profit_margin", "type":">", "value":0.85}]', 'text': 'Over +85%'},
{ "value" :  '[{"field":"net_profit_margin", "type":">", "value":0.50}]', 'text': 'Over +50% '},
{ "value" :  '[{"field":"net_profit_margin", "type":">", "value":0.25}]', 'text': 'Over +25%'},
{ "value" :  '[{"field":"net_profit_margin", "type":">", "value":0.20}]', 'text': 'Over +20%'},
{ "value" :  '[{"field":"net_profit_margin", "type":">", "value":0.15}]', 'text': 'Over +15%'},
{ "value" :  '[{"field":"net_profit_margin", "type":">", "value":0.10}]', 'text': 'Over +10%'},
{ "value" :  '[{"field":"net_profit_margin", "type":">", "value":0.05}]', 'text': 'Over +5%'},
{ "value" :  '[{"field":"net_profit_margin", "type":">", "value":0.03}]', 'text': 'Over +3%'},
{ "value" :  '[{"field":"net_profit_margin", "type":">", "value":0.02}]', 'text': 'Over +2%'},
{ "value" :  '[{"field":"net_profit_margin", "type":"<", "value":0.80}]', 'text': 'Under +85%'},
{ "value" :  '[{"field":"net_profit_margin", "type":"<", "value":0.50}]', 'text': 'Under +50%'},
{ "value" :  '[{"field":"net_profit_margin", "type":"<", "value":0.20}]', 'text': 'Under +20%'},
{ "value" :  '[{"field":"net_profit_margin", "type":"<", "value":0.15}]', 'text': 'Under +15%'},
{ "value" :  '[{"field":"net_profit_margin", "type":"<", "value":0.10}]', 'text': 'Under +10%'},
{ "value" :  '[{"field":"net_profit_margin", "type":"<", "value":0.05}]', 'text': 'Under +5%'},
{ "value" :  '[{"field":"net_profit_margin", "type":"<", "value":0.03}]', 'text': 'Under +3%'},
{ "value" :  '[{"field":"net_profit_margin", "type":"<", "value":0.02}]', 'text': 'Under +2%'},
{ "value" :  '[{"field":"net_profit_margin", "type":"<", "value":0.01}]', 'text': 'Under +1%'},
{ "value" :  '[{"field":"net_profit_margin", "type":"<", "value":-0.85}]', 'text': 'Under -85%'},
{ "value" :  '[{"field":"net_profit_margin", "type":"<", "value":-0.50}]', 'text': 'Under -50%'},
{ "value" :  '[{"field":"net_profit_margin", "type":"<", "value":-0.20}]', 'text': 'Under -20%'},
{ "value" :  '[{"field":"net_profit_margin", "type":"<", "value":-0.15}]', 'text': 'Under -15%'},
{ "value" :  '[{"field":"net_profit_margin", "type":"<", "value":-0.10}]', 'text': 'Under -10%'},
{ "value" :  '[{"field":"net_profit_margin", "type":"<", "value":-0.05}]', 'text': 'Under -5%'},
{ "value" :  '[{"field":"net_profit_margin", "type":"<", "value":-0.03}]', 'text': 'Under -3%'},
{ "value" :  '[{"field":"net_profit_margin", "type":"<", "value":-0.02}]', 'text': 'Under -2%'},
},
{ "value" :  '[{"field":"institutional_own", "type":">", "value":0.90}]', 'text': 'High (>90%)'},
{ "value" :  '[{"field":"institutional_own", "type":">", "value":0.80}]', 'text': 'Over 80% '},
{ "value" :  '[{"field":"institutional_own", "type":">", "value":0.65}]', 'text': 'Over 65%'},
{ "value" :  '[{"field":"institutional_own", "type":">", "value":0.50}]', 'text': 'Over 50%'},
{ "value" :  '[{"field":"institutional_own", "type":">", "value":0.25}]', 'text': 'Over 25%'},
{ "value" :  '[{"field":"institutional_own", "type":">", "value":0.15}]', 'text': 'Over 15%'},
{ "value" :  '[{"field":"institutional_own", "type":">", "value":0.10}]', 'text': 'Over 10%'},
{ "value" :  '[{"field":"institutional_own", "type":">", "value":0.05}]', 'text': 'Over 5%'},
{ "value" :  '[{"field":"institutional_own", "type":">", "value":0.01}]', 'text': 'Over 1%'},
{ "value" :  '[{"field":"institutional_own", "type":"<", "value":0.90}]', 'text': 'Under 90%'},
{ "value" :  '[{"field":"institutional_own", "type":"<", "value":0.80}]', 'text': 'Under 80%'},
{ "value" :  '[{"field":"institutional_own", "type":"<", "value":0.50}]', 'text': 'Under 50%'},
{ "value" :  '[{"field":"institutional_own", "type":"<", "value":0.25}]', 'text': 'Under 25%'},
{ "value" :  '[{"field":"institutional_own", "type":"<", "value":0.15}]', 'text': 'Under 15%'},
{ "value" :  '[{"field":"institutional_own", "type":"<", "value":0.10}]', 'text': 'Under 10%'},
{ "value" :  '[{"field":"institutional_own", "type":"<", "value":0.05}]', 'text': 'Under 5%'},
{ "value" :  '[{"field":"institutional_own", "type":"<", "value":0.01}]', 'text': 'Under 1%'},

**/

// export { };